# Generated by Django 5.2.7 on 2025-11-01 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('scanning', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Lácteo', 'Lácteo'), ('Carne', 'Carne'), ('Crema', 'Crema')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('lote', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Lácteo', 'Lácteo'), ('Carne', 'Carne'), ('Crema', 'Crema')], max_length=50)),
                ('scanning_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.producto')),
            ],
        ),
    ]
